

seq = "TGATTGGATGAAAATGATGTAGTAATGACAACACAGAAGGTGTAAGGAACTGAATCTGAAAAAACATTAGATCCTGCTAAAAGTCTCACTGACTAAGGAATTGAAACTCACGGCTATAAAAAGATCGCAGTCATTTAGTAC"

def parse_seq(s,k=17):
    l = len(s)
    
    

def main():
    import networkx as nx